name: En route
favicon: null
layout_spectrum: 0.24351
typography_spectrum: 0.6426354853902012
title: 'Travel stories from Kate & Chris'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6db8f1'
    - '#fffebe'
    - '#764b3b'
    - '#241613'
    - '#e0933d'
  brandStrength: 0.5322741365525872
  lightness: 0.047071245266124606
  saturation: 0.6040828335098922
  rhythmicContrast: 0.5789563192520291
purpose: []
