layout_spectrum: 0.3351254
typography_spectrum: 0.5085114883258939
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.483864702982828
  lightness: 0.067209581611678
  saturation: 0.7438423393759876
  rhythmicContrast: 0.3716406349558383
name: En route
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Travel stories from Kate & Chris
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
